### PR TITLE
3 individual changes

### PR DESCRIPTION
**Pull request by erezsh**

### CODE REVIEW

**Comment by dbrodie** [comment]
(I'll respond to the patches in a reverse order)
A. I don't like that solution. I think the better solution would be to have a newtype for the only nibble offset value in the struct, and wrap it with the [custom_derive crate](https://danielkeep.github.io/rust-custom-derive/doc/newtype_derive/index.html) for the numeric operations. I just hadn't had a chance to do it yet.
B. Thanks for the bugfix! :)
C. This is a good idea, but I would like this to be more generic (for example, supporting a 2 byte offset, little/big endian, relative/absolute, etc...) and possibly more obvious (if you are standing somewhere, which bytes are taken? Maybe have a preview of the offset?). As a simple stopgap, I think that when starting a goto operation, having the UI fill in based on the current selection, should be a descent solution.

If you want to work on any of it, just tell me, I'll leave it open for now. If it's OK by you I'll cherry-pick the bugfix, unless you want to open a new pull request on it.

Thank you!

**Comment by erezsh** [comment]
If I understand A correctly, your solution sounds better. So feel free to
cherry pick.

Well, I added option C because I needed it, so I agree it's not very
elegant.
My first thought was to have Ctrl-D, Ctrl-W and Ctrl-B for dwords, words
and bytes, and to have endianity and rel/abs as modes (like
insert/overwrite).
But I agree it would be prettier with UI support. So here's another idea:
You enter ptr-mode (maybe by pressing Ctrl+p or Ctrl+*), which highlights
the byte/word/dword that will be followed, and you can also cycle between
them (like the other modes) and follow by pressing Enter.
Which makes it a little more like vim, I guess, but makes it easier to
navigate a file format (especially if I add a "jump back" shortcut).

-- OR --
Maybe the dword/word mode should be part of the editor, and allow you to
edit words and dwords (with endianity of course) and not just  bytes. So
then the *follow-ptr *operator will be just another in a list of actions
you can take on what's highlighted, just like cut or copy.
I think this last option gives the best value per effort :)

What do you think?

**Comment by dbrodie** [comment]
Yeah that is pretty much what I was thinking, (though, you can't use ctrl-*, due to bad terminal, at best you can use ctrl-8 :/ ), maybe having as part of an "inspector" style window, similar to this feature in other hex editors.
010-inspector

**Comment by dbrodie** [comment]
OK, from the original patch set:
A & B are done and in master - Thank you.
C - We can follow up in a dedicated issue - #4. I want the UI on it to be decent.

**Pull request closed without merging**
